---
- name: Install iwd
  pacman:
    name: iwd
    state: present

- name: Enable systemd-networkd
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - systemd-networkd
    - systemd-resolved
    - iwd

- name: Copy network configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-networkd
  with_items:
    - 20-wired.network
    - 25-wireless.network

- import_tasks: tools.yml
  tags: networking-tools
