---
- name: Install networking tools
  community.general.pacman:
    name:
      - gping
      - speedtest-cli
      # - whois
      # - netcat
      # - nmap
      # - tcpdump
      # - wireshark
      # - inetutils
    state: present
