---
- name: Install networking tools
  community.general.pacman:
    name:
      - gping
      - bind
      # - whois
      # - netcat
      # - nmap
      - tcpdump
      # - wireshark
      # - inetutils
    state: present

- name: Install optional networking tools
  community.general.pacman:
    name:
      - speedtest-cli
    state: present
  tags: speedtest
