---
- hosts: all
  become: true

  # vars_prompt:
  #   - name: password
  #     prompt: Password
  #     private: true
  #     confirm: true
  #     unsafe: true
  #     encrypt: bcrypt
  #     salt_size: 8

  pre_tasks:
    - name: Check if system is virtual
      lineinfile:
        path: /sys/devices/virtual/dmi/id/sys_vendor
        line: QEMU
        state: present
      check_mode: true
      register: virtual
      failed_when: (virtual is failed) or (virtual is changed)
      ignore_errors: true
      tags: always

    - name: Platform is physical
      set_fact:
        physical: true
        virtual: false
      when: virtual is failed
      tags: always

    - name: Platform is virtual
      set_fact:
        physical: false
        virtual: true
      when: virtual
      tags: always

  roles:
    - role: base
    - role: networking
    - role: security

    - role: audio
      tags: ['audio']

    - role: bluetooth
      when: physical
      tags: ['bluetooth']

    - role: gui
      tags: ['gui']

    - role: laptop
      when: physical
      tags: ['laptop']

    - role: dev
      tags: ['dev']
    - role: play
      tags: ['play']
    - role: office
      tags: ['office']

    - role: print
      when: physical
      tags: ['print']

    - role: ricing
      tags: ['ricing']

    - role: disk
      when: physical
      tags: ['disk']
