---
- hosts: all
  become: true
  vars:
    user: user
    password: password
  roles:
    - base
    - networking
    - security

    - role: audio
      tags: ['audio']
    - role: bluetooth
      tags: ['bluetooth']
    - role: gui
      tags: ['gui']
    - role: laptop
      tags: ['laptop']
    - role: dev
      tags: ['dev']
    - role: play
    - role: office
      tags: ['office']
    - role: print
      tags: ['print']
    - role: ricing
      tags: ['ricing']
    - role: disk
      tags: ['disk']
