---
- hosts: all
  become: true

  # vars_prompt:
  #   - name: password
  #     prompt: Password
  #     private: true
  #     confirm: true
  #     unsafe: true
  #     encrypt: bcrypt
  #     salt_size: 8

  vars:
    user: kenc
    password: changeme
    shell: /bin/zsh
    network_static_ip: true
    network_ip_addr: "192.168.86.82/24"
    network_gw: "192.168.86.1"
    network_dns: "192.168.86.49"
    network_routes:
      - gw: "192.168.86.6"
        dest: "10.10.10.0/24"
    gui_video_driver: nvidia
    print_driver: brother-hl1210w

  pre_tasks:
    - name: Check if system is virtual
      lineinfile:
        path: /sys/devices/virtual/dmi/id/sys_vendor
        line: QEMU
        state: present
      check_mode: true
      register: virtual
      failed_when: (virtual is failed) or (virtual is changed)
      ignore_errors: true

    - name: Platform is physical
      set_fact:
        physical: true
        virtual: false
      when: virtual is failed

    - name: Platform is virtual
      set_fact:
        physical: false
        virtual: true
      when: virtual

  roles:
    - base
    - networking
    - security

    - role: audio
      tags: ['audio']

    - role: bluetooth
      when: physical
      tags: ['bluetooth']

    - role: gui
      tags: ['gui']

    - role: laptop
      when: physical
      tags: ['laptop']

    - role: dev
      tags: ['dev']
    - role: play
      tags: ['play']
    - role: office
      tags: ['office']

    - role: print
      when: physical
      tags: ['print']

    - role: ricing
      tags: ['ricing']

    - role: disk
      when: physical
      tags: ['disk']
