---
- name: Setup nftables
  import_tasks: nftables.yml
  tags: nftables

- name: Setup iptables
  when: "'nftables' not in ansible_run_tags"
  block:
    - name: Install iptables
      community.general.pacman:
        name:
          - iptables
        state: present

    - name: Start and enable iptables
      systemd:
        name: iptables
        state: started
        enabled: true

- name: Install ufw
  community.general.pacman:
    name: ufw
    state: present

- name: Enable and configure ufw incoming/outgoing rules
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
    - {direction: outgoing, policy: allow}
    - {direction: incoming, policy: deny}

- name: Configure ufw ports
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment | default('') }}"
  with_items: "{{ ufw_default_rules + ufw_rules }}"
  notify: restart ufw
