---
- name: Install nftables
  community.general.pacman:
    name:
      - nftables
    state: present
  register: nftables

# shell command is necessary to force remove iptables due to
# iptables dependency in systemd
- name: Install iptables-nft
  shell: |
    set -o pipefail
    yes | pacman -S iptables-nft
  when: nftables is changed

- name: Remove iptables
  community.general.pacman:
    name: iptables
    state: absent

- name: Add nftables.service
  template:
    src: nftables.service.j2
    dest: /etc/systemd/system/nftables.service
    owner: root
    group: root
    mode: 0644
  notify: reload nftables

# TODO replace docker iptables rules with nftables
# TODO bind fail2ban to nftables

- name: Start nftables
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - nftables
    - iptables

- name: Install ufw
  community.general.pacman:
    name: ufw
    state: present

- name: Enable and configure ufw incoming/outgoing rules
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
    state: enabled
  with_items:
    - {direction: outgoing, policy: allow}
    - {direction: incoming, policy: deny}

- name: Configure ufw ports
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment | default('') }}"
  with_items: "{{ ufw_default_rules + ufw_rules }}"
  notify: restart ufw
