---
- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted

- name: update arch repo mirrors
  command: reflector @/etc/xdg/reflector/reflector.conf

- name: rebuild grub
  command: grub-mkconfig -o /boot/grub/grub.cfg
