---
# https://wiki.archlinux.org/title/Xorg#Driver_installation
- name: Install required video drivers
  community.general.pacman:
    name: "{{ gui_video_driver }}"
    state: present
  notify: regenerate initramfs

- name: Install Nvidia drivers
  community.general.pacman:
    name:
      - nvidia-utils
      - lib32-nvidia-utils
    state: present
  when: '"nvidia" in gui_video_driver'
  notify: regenerate initramfs

- name: Install AMD drivers
  community.general.pacman:
    name:
      - mesa
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - rocm-smi-lib  # required for btop
    state: present
  when: '"xf86-video-amdgpu" in gui_video_driver'
  notify: regenerate initramfs

- name: Install Intel drivers
  community.general.pacman:
    name:
      - mesa
      - lib32-mesa
      - vulkan-intel
      - lib32-vulkan-intel
    state: present
  when: '"xf86-video-intel" in gui_video_driver'
  notify: regenerate initramfs

- name: Copy nvidia.hook
  copy:
    src: nvidia.hook
    dest: /etc/pacman.d/hooks/nvidia.hook
    owner: root
    group: root
    mode: 0644
  when: '"nvidia" in gui_video_driver'
