---
- name: Install Xorg
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xterm
    state: present

- import_tasks: driver.yml
  when: gui_video_driver != ""

- name: Add user to video group
  user:
    name: "{{ user }}"
    groups: video
    append: true

- name: Install window manager
  pacman:
    name:
      - bspwm
      - sxhkd
    state: present

- name: Copy .xinitrc template
  copy:
    src: xinitrc
    dest: "/home/{{ user }}/.xinitrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

# this is only relevant if the user's default shell is /bin/bash
# other shells must add their own startup files via custom dotfiles
- name: Copy .bash_profile template to autostart X at login
  copy:
    src: bash_profile
    dest: "/home/{{ user }}/.bash_profile"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

# only run if not ricing
# otherwise, stow will fail later
- name: Create bspwm and sxhkd $XDG_CONFIG_HOME directories
  file:
    path: "/home/{{ user }}/.config/{{ item }}"
    owner: kenc
    group: kenc
    mode: 0755
    state: directory
  with_items:
    - bspwm
    - sxhkd
  when: "'ricing' not in ansible_run_tags"

- name: Copy default bspwmrc and sxhkdrc
  copy:
    src: "/usr/share/doc/bspwm/examples/{{ item.src }}"
    dest: "/home/{{ user }}/.config/{{ item.dest }}"
    remote_src: true
    force: false
  with_items:
    - src: bspwmrc
      dest: bspwm/bspwmrc
    - src: sxhkdrc
      dest: sxhkd/sxhkdrc
  when: "'ricing' not in ansible_run_tags"

# config set in dotfiles
- name: Install Redshift
  pacman:
    name: redshift
    state: present
  tags: redshift

- import_tasks: multi_monitor.yml
  tags: multi-monitor
