---
- name: Install cups
  community.general.pacman:
    name: cups
    state: present

# Socket based activation only
- name: Enable cups.socket
  systemd:
    name: cups.socket
    state: started
    enabled: true

- name: Disable cups.service
  systemd:
    name: cups.service
    state: stopped
    enabled: false

- name: Install printer driver
  kewlfft.aur.aur:
    name: "{{ print_driver }}"
    use: makepkg
    state: present
  when: print_driver != ""
