---
- name: Install libreoffice
  community.general.pacman:
    name:
      - libreoffice-still
    state: present
  tags: libreoffice

- name: Install libqalculate
  community.general.pacman:
    name: libqalculate
    state: present

- name: Install xsv
  community.general.pacman:
    name: xsv
    state: present
  tags: xsv

- name: Install zathura
  community.general.pacman:
    name: zathura
    state: present

- name: Install zathura epub support
  community.general.pacman:
    name: zathura-pdf-mupdf
    reason: dependency
    state: present
  tags: zathura-extras

- name: Install pdfcpu
  pacman:
    name: pdfcpu
    state: present
  tags:
    - pdfcpu
    - aur

- name: Install Obsidian
  community.general.pacman:
    name: obsidian
    state: present
  tags: obsidian

- name: Install pcmanfm file manager
  community.general.pacman:
    name: pcmanfm-gtk3
    state: present
  tags: pcmanfm

- name: Install pandoc-bin
  pacman:
    name: pandoc-bin
    state: present
  tags:
    - pandoc
    - aur
