---
# TODO install noto-fonts for universal font coverage

- name: Install libreoffice
  pacman:
    name:
      - libreoffice-still
    state: present
  tags: libreoffice

- name: Install libqalculate
  pacman:
    name: libqalculate
    state: present

- name: Install xsv
  pacman:
    name: xsv
  state: present
  tags: xsv

- name: Install zathura
  pacman:
    name:
      - zathura
    state: present

- name: Install zathura epub support
  pacman:
    name:
      - zathura-pdf-mupdf
    state: present
  tags: zathura-extras

- name: Install Obsidian
  pacman:
    name:
      - obsidian
    state: present
  tags: obsidian
