---
base_packages:
  - base-devel
  - btrfs-progs
  - vim
  - git
  - tmux
  - curl
  - wget
  - bc
  - python
  - logrotate
  - dosfstools
  - gocryptfs
  - fzf
  - fd
  - ripgrep
  - zoxide
  - bat
  - ncdu
  - xclip
  - xdotool
  - libnotify
  - scrot
  - glow
  - hugo
  - imagemagick
  - yt-dlp

shell: /bin/bash
user: arch
password: changeme
base_timezone: Asia/Singapore
base_locale: "en_US.UTF-8"
base_hostname: "arch"
base_fonts:
  - noto-fonts
  - noto-fonts-emoji
  - ttf-liberation

base_add_custom_repo: false
base_custom_repo_name: "custom"
base_custom_repo_sig_level: "Optional TrustAll"
base_custom_repo_url: "file:///var/cache/pacman/{{ base_custom_repo_name }}"
base_aur_packages:
  - aurutils
  - gotop-bin
  - anki-official-binary-bundle
