---
- import_tasks: power.yml

# TODO close lid

# brightness
- name: Install xbacklight
  community.general.pacman:
    name: xorg-xbacklight
    state: present

# brightness hotkeys

# touchpad
- name: Install libinput
  community.general.pacman:
    name:
      - libinput
      - xf86-input-libinput
    state: present

- name: Copy touchpad.conf
  copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    owner: root
    group: root
    mode: 0644

# TODO
# - name: Install libinput-gestures from AUR

- name: Add user to input group
  user:
    name: "{{ user }}"
    groups: input
    append: true

- name: Copy libinput-gestures.conf
  copy:
    src: libinput-gestures.conf
    dest: "/home/{{ user }}/.config/libinput-gestures.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

# TODO make idempotent
- name: Start libinput-gestures
  command: libinput-gestures-setup autostart start

# webcam device
- name: Install v4l2-ctl
  community.general.pacman:
    name: v4l2-ctl
    state: present
