---
- name: Install pipewire and related support packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - pipewire
    - pipewire-pulse
    - pipewire-alsa
    - pipewire-jack

- name: Get UID of {{ user }}
  command: "id -u {{ user }}"
  changed_when: false
  check_mode: false
  register: uid

- name: Populate XDG_RUNTIME_DIR
  set_fact:
    xdg_runtime_dir: "/run/user/{{ uid.stdout }}"
  changed_when: false

- name: Enable pipewire user service
  become: true
  become_user: "{{ user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  with_items:
    - pipewire
    - pipewire-pulse

# - name: Install wireplumber
#   pacman:
#     name: wireplumber
#     state: present
#
# - name: Enable wireplumber user service
#   systemd:
#     name: wireplumber
#     state: started
#     enabled: true
#     scope: user
