---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Update cache
      community.general.pacman:
        update_cache: true
      changed_when: false

- import_playbook: ../../main.yml
