---
user: kenc
password: changeme
shell: /bin/zsh
network_static_ip: true
network_wireless_ip_addr: "192.168.86.82/24"
network_gw: "192.168.86.1"
network_dns: "192.168.86.49"
network_routes:
  - gw: "192.168.86.6"
    dest: "10.10.10.0/24"
gui_video_driver: nvidia
print_driver: brother-hl1210w

ufw_rules:
  - {rule: 'allow', port: '22000', proto: 'tcp', comment: 'syncthing'}
  - {rule: 'allow', port: '21027', proto: 'udp', comment: 'syncthing'}

aur_user: "{{ user }}"
aur_remote_s3_repo: true
aur_s3_endpoint: "https://minio.kencv.xyz"
aur_remote_s3_bucket: "aur"
