---
- name: Install stow
  community.general.pacman:
    name: stow
    state: present

- name: Check if dotfiles dir exists
  stat:
    path: "/home/{{ user }}/dotfiles"
  register: dots

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_url }}"
    dest: "/home/{{ user }}/dotfiles"
    version: HEAD
    accept_hostkey: true
  when: dots.stat.isdir is defined and not dots.stat.isdir

# TODO use module
- name: stow dotfiles
  command:
    cmd: make stow
    chdir: "/home/{{ user }}/dotfiles"

# check for failure
