---
- name: Install stow
  community.general.pacman:
    name: stow
    state: present

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_url }}"
    dest: "/home/{{ user }}/dotfiles"
    version: HEAD
    accept_hostkey: true
    recursive: true
