---
- name: Install rice packages
  community.general.pacman:
    name:
      - rofi
      - dunst
      - nsxiv
      - feh
    state: present

- name: Install Nerd Font
  community.general.pacman:
    name: "{{ ricing_nerd_font }}"
    state: present

- name: Install rice packages from AUR
  community.general.pacman:
    name:
      - eww
      - pfetch
      - zsh-pure-prompt
    state: present
  tags: aur

- import_tasks: dotfiles.yml
- import_tasks: neovim.yml
  tags: neovim

- name: Get "{{ ricing_user }}" uid
  getent:
    database: passwd
    key: "{{ ricing_user }}"

- set_fact:
    xdg_runtime_dir: "/run/user/{{ getent_passwd[vars['ricing_user']][1] }}"
  changed_when: false

- name: Start redshift user service
  become: true
  become_user: "{{ ricing_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: redshift
    state: started
    enabled: true
    scope: user

- name: Start dunst user service
  become: true
  become_user: "{{ ricing_user }}"
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
  systemd:
    name: dunst
    state: started
    enabled: true
    scope: user
