---

- name: Install rice packages
  pacman:
    name:
      - rofi
      - dunst
      # - picom
      # - starship
      # - slock
    state: present

- import_tasks: fonts.yml
- import_tasks: eww.yml
- import_tasks: firefox.yml
  tags: firefox
- import_tasks: neovim.yml
  tags: neovim
