---
- name: Install rice packages
  pacman:
    name:
      - rofi
      - dunst
      # - picom
      # - starship
      # - slock
    state: present

- name: Install fonts
  pacman:
    name:
      - ttf-firacode-nerd
      - noto-fonts
    state: present

- import_tasks: eww.yml
- import_tasks: dotfiles.yml
- import_tasks: firefox.yml
  tags: firefox
- import_tasks: neovim.yml
  tags: neovim
