---
- name: Install neovim
  pacman:
    name:
      - neovim
    state: present

- name: Install neovim plugins
  command: |
    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
