---
- name: Install neovim
  community.general.pacman:
    name:
      - neovim
    state: present

- name: Install neovim plugins
  command: |
    nvim --headless "+Lazy! sync" +qa

- name: Pull lspcontainers images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
    state: present
  with_items: "{{ ricing_neovim_lspcontainers }}"
