---
- name: Add custom repository file to /etc/pacman.d
  template:
    src: "aur_custom_repo.j2"
    dest: "/etc/pacman.d/{{ base_custom_repo_name }}"
    owner: root
    group: root
    mode: 0644

- name: Add custom remote repository
  lineinfile:
    path: /etc/pacman.conf
    line: Include = /etc/pacman.d/{{ base_custom_repo_name }}
    owner: root
    group: root
    mode: 0644

- name: Install AUR packages
  pacman:
    name: "{{ base_aur_packages }}"
    state: present
    update_cache: true
