---

# TODO set up bootloader/grub

- set_fact:
    vendor: intel
  when:
    - ansible_processor is defined
    - "'Intel' in ansible_processor | join(' ')"

- set_fact:
    vendor: amd
  when:
    - ansible_processor is defined
    - "'AMD' in ansible_processor | join(' ')"

- name: Install microcode
  pacman:
    name: "{{ vendor }}-ucode"
    state: present
  when:
    - vendor is defined
    - physical
  # notify: rebuild grub

- name: Install backup kernel
  pacman:
    name: linux-lts
    state: present
  # notify: rebuild grub

- name: Set top level menu entry
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_TOP_LEVEL=/boot/vmlinuz-linux'
    state: present
  # notify: rebuild grub
