---
- name: Install base packages
  pacman:
    name: "{{ base_packages }}"
    state: present
    update_cache: true

- name: Install bash
  pacman:
    name:
      - bash
      - bash-completion
    state: present

- name: Install zsh
  pacman:
    name:
      - zsh
      - zsh-completions
    state: present

- import_tasks: user.yml
- import_tasks: pacman.yml
- import_tasks: boot.yml
- import_tasks: journald.yml

- name: Install man pages
  pacman:
    name:
      - man-db
      - man-pages
    state: present

- name: Run mandb
  command: mandb

- name: Enable fstrim.timer
  systemd:
    name: fstrim.timer
    state: started
    enabled: true
