---
- import_tasks: pacman.yml

- name: Install base packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
    update_cache: true

- name: Install bash
  community.general.pacman:
    name:
      - bash
      - bash-completion
    state: present

- name: Install zsh
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
    state: present

- name: Set timezone
  community.general.timezone:
    name: "{{ base_timezone }}"
  register: tz

- name: Sync time to hwclock
  ansible.builtin.command: hwclock --systohc
  when: tz is changed

- name: Set locale
  community.general.locale_gen:
    name: "{{ base_locale }}"
    state: present

- name: Set hostname
  hostname:
    name: "{{ base_hostname }}"

- import_tasks: user.yml
- import_tasks: boot.yml
- import_tasks: journald.yml

- name: Install man pages
  community.general.pacman:
    name:
      - man-db
      - man-pages
    state: present

- name: Install fonts
  community.general.pacman:
    name: "{{ base_fonts }}"
    state: present

- name: Enable fstrim.timer
  systemd:
    name: fstrim.timer
    state: started
    enabled: true

- import_tasks: aur.yml
  when: base_add_custom_repo
  tags: aur
