---
- name: Install sudo
  community.general.pacman:
    name: sudo
    state: present

- name: Create wheel group
  group:
    name: wheel
    state: present

- name: Create user
  user:
    name: "{{ user }}"
    shell: "{{ shell }}"
    groups: wheel
    append: true
    create_home: true
    password: "{{ password | password_hash('sha512') }}"
    update_password: on_create
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    state: present
  register: user_output

- name: Copy sudoers file
  template:
    src: sudo_wheel.j2
    dest: /etc/sudoers.d/01_wheel
    owner: root
    group: root
    mode: 0440
    validate: 'visudo -cf %s'

- name: Create user .ssh directory
  file:
    path: "/home/{{ user }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    state: directory

- name: Create user socket directory
  file:
    path: "/run/user/{{ user_output.uid }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
    state: directory

- name: Start user systemd instance
  systemd:
    name: user@{{ user_output.uid }}
    state: started
