---
- name: Install Ansible core
  community.general.pacman:
    name:
      - ansible-core
    state: present

- name: Install Ansible extras
  community.general.pacman:
    name:
      - ansible
      - ansible-lint
    state: present
  tags: ansible-extras

# TODO ansible.cfg
# - name: Copy default ansible.cfg

- name: Install molecule
  community.general.pacman:
    name:
      - molecule
      - molecule-plugins
    reason: dependency
    state: present
  tags: molecule
