---
- name: Install Docker
  community.general.pacman:
    name:
      - docker
      - docker-compose
      - docker-buildx

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Create /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy docker daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: "root"
    group: "root"
    mode: 0644
    validate: "dockerd --validate --config-file=%s"
  notify: restart docker

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: true

# TODO install dive from aur
