---
- name: Install Go and tools
  community.general.pacman:
    name:
      - go
      - go-tools
      - gopls
    state: present
  tags: golang

- name: Install Go tools from AUR
  community.general.pacman:
    name:
      - air
      - templ-bin
    state: present
  tags:
    - golang
    - aur

- name: Install Python and tools
  community.general.pacman:
    name:
      - python
      - python-pip
      - python-pipx
      - python-virtualenv
      - python-lsp-server
      - flake8
      - pyenv
    state: present

- name: Install rustup
  community.general.pacman:
    name:
      - rustup
    state: present
  tags: rustup

- import_tasks: ruby.yml
  tags: ruby

- import_tasks: haskell.yml
  tags: haskell

- name: Install linters
  community.general.pacman:
    name:
      - yamllint
      - stylua
      - luacheck
      - codespell
      - shfmt
    state: present
  tags: linters

- name: Install shellcheck
  community.general.pacman:
    name: shellcheck-bin
    state: present
  tags: aur

- name: Install other tools
  community.general.pacman:
    name:
      - jq
      - direnv
      - sops
      - age
      - mkcert
    state: present

- name: Install minio client
  community.general.pacman:
    name: minio-client
    state: present
  tags: minio

- name: Install flyctl-bin
  community.general.pacman:
    name: flyctl-bin
    state: present
  tags:
    - fly
    - aur

- import_tasks: docker.yml
  tags: docker

- import_tasks: qemu.yml
  tags: qemu

- import_tasks: virtualbox.yml
  tags: virtualbox

- import_tasks: ansible.yml
  tags: ansible

- import_tasks: hashicorp.yml
  tags: hashicorp
