---
- name: Install Go and tools
  community.general.pacman:
    name:
      - go
      - go-tools
      - gopls
    state: present
  tags: golang

- name: Install Python and tools
  community.general.pacman:
    name:
      - python
      - python-pip
      - python-pipx
      - python-virtualenv
      - python-lsp-server
      - flake8
      - pyenv
    state: present

- name: Install rustup
  community.general.pacman:
    name:
      - rustup
    state: present
  tags: rustup

- name: Install linters
  community.general.pacman:
    name:
      - yamllint
      - stylua
      - luacheck
      - codespell
      - shfmt
    state: present
  tags: linters

- name: Install other tools
  community.general.pacman:
    name:
      - jq
      - direnv
      - sops
      - age
    state: present

- import_tasks: docker.yml
  tags: docker

- import_tasks: qemu.yml
  tags: qemu

- import_tasks: ansible.yml
  tags: ansible

- import_tasks: hashicorp.yml
  tags: hashicorp
