---
- name: Install qemu
  pacman:
    name: qemu-desktop
    state: present

- name: Install libvirt
  pacman:
    name: libvirt
    state: present

- name: Install libvirt dependencies
  pacman:
    name:
      - dnsmasq
      - dmidecode
      - bridge-utils
      - openbsd-netcat
    reason: dependency
    state: present

- name: Add user to libvirt group
  user:
    name: "{{ user }}"
    groups: libvirt
    append: true

# - name: Start libvirtd
#   systemd:
#     name: libvirtd
#     state: started
#     enabled: true

- name: Install virt-manager
  pacman:
    name: virt-manager
    state: present
