---
- name: Install virtualbox-host-modules-arch
  community.general.pacman:
    name: virtualbox-host-modules-arch
    state: present

- name: Install virtualbox-guest-iso
  community.general.pacman:
    name: virtualbox-guest-iso
    state: present
