---
- name: Install firefox
  community.general.pacman:
    name:
      - firefox
    state: present
  tags: firefox

# TODO setup extensions

- name: Install telegram
  community.general.pacman:
    name: telegram-desktop
    state: present

- name: Install yt-dlp
  community.general.pacman:
    name: yt-dlp
    state: present

- name: Install mpv
  community.general.pacman:
    name: mpv
    state: present

- name: Install discord
  community.general.pacman:
    name: discord
    state: present
  tags: discord

- import_tasks: music.yml
  tags: music

- import_tasks: steam.yml
  tags: steam
