---
- name: Install telegram
  community.general.pacman:
    name: telegram-desktop
    state: present

- name: Install mpv
  community.general.pacman:
    name: mpv
    state: present

- name: Install discord
  community.general.pacman:
    name: discord
    state: present
  tags: discord

- import_tasks: music.yml
  tags: music

- import_tasks: steam.yml
  tags: steam

- name: Install factorio
  pacman:
    name: factorio
    state: present
  tags:
    - aur
    - factorio
