---
- name: Install telegram
  community.general.pacman:
    name: telegram-desktop
    state: present

- name: Install mpv
  community.general.pacman:
    name: mpv
    state: present

- name: Install discord
  community.general.pacman:
    name: discord
    state: present
  tags: discord

- name: Install melonds (DS emulator)
  community.general.pacman:
    name: melonds-bin
    state: present
  tags:
    - melonds
    - aur

- name: Install factorio
  community.general.pacman:
    name: factorio
    state: present
  tags:
    - factorio
    - aur

- import_tasks: music.yml
  tags: music

- import_tasks: steam.yml
  tags: steam
