---
- name: Install firefox
  pacman:
    name:
      - firefox
    state: present
  tags: firefox

# TODO setup extensions

- name: Install telegram
  pacman:
    name:
      - telegram-desktop
    state: present

- name: Install steam
  pacman:
    name:
      - steam
    state: present
  tags: steam

# TODO install proton from aur

- import_tasks: music.yml
  tags: music
