---
- name: Install firefox
  pacman:
    name:
      - firefox
    state: present
  tags: firefox

# TODO setup extensions

- name: Install telegram
  pacman:
    name: telegram-desktop
    state: present

- name: Install discord
  pacman:
    name: discord
    state: present
  tags: discord

- import_tasks: music.yml
  tags: music

- import_tasks: steam.yml
  tags: steam
