---
- name: Enable multilib repository
  replace:
    path: /etc/pacman.conf
    regexp: '#\[multilib\]\n#(Include = /etc/pacman.d/mirrorlist)'
    replace: '[multilib]\n\1'
    backup: true

# See https://wiki.archlinux.org/title/Steam#Installation
- name: Install steam
  community.general.pacman:
    name: steam
    state: present

- name: Install steam dependencies
  community.general.pacman:
    name:
      - nvidia-utils
      - lib32-nvidia-utils
      - lib32-systemd
    reason: dependency
    state: present

- name: Create custom steam directory
  file:
    path: "/mnt/games"
    owner: root
    group: root
    mode: 0755
    state: directory

# Manually move Steam directory to new custom location
