---
ricing_user: "arch"
ricing_nerd_font: "ttf-firacode-nerd"
ricing_neovim_lspcontainers:
  - lspcontainers/bash-language-server
  - lspcontainers/terraform-ls
  - lspcontainers/lua-language-server
  - lspcontainers/yaml-language-server
  - lspcontainers/typescript-language-server
  - lspcontainers/svelte-language-server
  - lspcontainers/docker-language-server
