---
- name: restart ssh
  systemd:
    name: sshd
    state: restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: restart ufw
  community.general.ufw:
    state: reloaded

- name: reload nftables
  systemd:
    name: nftables
    daemon_reload: true
    state: restarted
